// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Dream.Space.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterViewStrategy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterViewStrategy));
        
        string IMigrationMetadata.Id
        {
            get { return "201612241153559_AlterViewStrategy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
