// <auto-generated />
namespace Dream.Space.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CompanySector : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompanySector));
        
        string IMigrationMetadata.Id
        {
            get { return "201703101532285_CompanySector"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
